/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AlertModification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-15T00:21:04.781159+02:00[Europe/Kiev]")

public class AlertModification {
  @SerializedName("lastActionIndex")
  private Long lastActionIndex = null;

  public AlertModification lastActionIndex(Long lastActionIndex) {
    this.lastActionIndex = lastActionIndex;
    return this;
  }

   /**
   * Get lastActionIndex
   * @return lastActionIndex
  **/
  @Schema(description = "")
  public Long getLastActionIndex() {
    return lastActionIndex;
  }

  public void setLastActionIndex(Long lastActionIndex) {
    this.lastActionIndex = lastActionIndex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertModification alertModification = (AlertModification) o;
    return Objects.equals(this.lastActionIndex, alertModification.lastActionIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastActionIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertModification {\n");
    
    sb.append("    lastActionIndex: ").append(toIndentedString(lastActionIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
