/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AlertType
 */
@JsonAdapter(AlertType.Adapter.class)
public enum AlertType {
  @SerializedName("UNKNOWN")
  UNKNOWN("UNKNOWN"),
  @SerializedName("AIR")
  AIR("AIR"),
  @SerializedName("ARTILLERY")
  ARTILLERY("ARTILLERY"),
  @SerializedName("URBAN_FIGHTS")
  URBAN_FIGHTS("URBAN_FIGHTS"),
  @SerializedName("CHEMICAL")
  CHEMICAL("CHEMICAL"),
  @SerializedName("NUCLEAR")
  NUCLEAR("NUCLEAR"),
  @SerializedName("INFO")
  INFO("INFO");

  private String value;

  AlertType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AlertType fromValue(String input) {
    for (AlertType b : AlertType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AlertType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AlertType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public AlertType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return AlertType.fromValue((String)(value));
    }
  }
}
