/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Alert;
import io.swagger.client.model.V2RegionType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * AlertRegionModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-15T00:21:04.781159+02:00[Europe/Kiev]")

public class AlertRegionModel {
  @SerializedName("regionId")
  private String regionId = null;

  @SerializedName("regionType")
  private V2RegionType regionType = null;

  @SerializedName("regionName")
  private String regionName = null;

  @SerializedName("regionEngName")
  private String regionEngName = null;

  @SerializedName("lastUpdate")
  private OffsetDateTime lastUpdate = null;

  @SerializedName("activeAlerts")
  private List<Alert> activeAlerts = null;

  public AlertRegionModel regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public AlertRegionModel regionType(V2RegionType regionType) {
    this.regionType = regionType;
    return this;
  }

   /**
   * Get regionType
   * @return regionType
  **/
  @Schema(description = "")
  public V2RegionType getRegionType() {
    return regionType;
  }

  public void setRegionType(V2RegionType regionType) {
    this.regionType = regionType;
  }

  public AlertRegionModel regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  @Schema(description = "")
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public AlertRegionModel regionEngName(String regionEngName) {
    this.regionEngName = regionEngName;
    return this;
  }

   /**
   * Get regionEngName
   * @return regionEngName
  **/
  @Schema(description = "")
  public String getRegionEngName() {
    return regionEngName;
  }

  public void setRegionEngName(String regionEngName) {
    this.regionEngName = regionEngName;
  }

  public AlertRegionModel lastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public AlertRegionModel activeAlerts(List<Alert> activeAlerts) {
    this.activeAlerts = activeAlerts;
    return this;
  }

  public AlertRegionModel addActiveAlertsItem(Alert activeAlertsItem) {
    if (this.activeAlerts == null) {
      this.activeAlerts = new ArrayList<Alert>();
    }
    this.activeAlerts.add(activeAlertsItem);
    return this;
  }

   /**
   * Get activeAlerts
   * @return activeAlerts
  **/
  @Schema(description = "")
  public List<Alert> getActiveAlerts() {
    return activeAlerts;
  }

  public void setActiveAlerts(List<Alert> activeAlerts) {
    this.activeAlerts = activeAlerts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertRegionModel alertRegionModel = (AlertRegionModel) o;
    return Objects.equals(this.regionId, alertRegionModel.regionId) &&
        Objects.equals(this.regionType, alertRegionModel.regionType) &&
        Objects.equals(this.regionName, alertRegionModel.regionName) &&
        Objects.equals(this.regionEngName, alertRegionModel.regionEngName) &&
        Objects.equals(this.lastUpdate, alertRegionModel.lastUpdate) &&
        Objects.equals(this.activeAlerts, alertRegionModel.activeAlerts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionId, regionType, regionName, regionEngName, lastUpdate, activeAlerts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertRegionModel {\n");
    
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    regionType: ").append(toIndentedString(regionType)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    regionEngName: ").append(toIndentedString(regionEngName)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    activeAlerts: ").append(toIndentedString(activeAlerts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
