/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.RegionAlarmModel;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RegionAlarmsHistory
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-15T00:21:04.781159+02:00[Europe/Kiev]")

public class RegionAlarmsHistory {
  @SerializedName("regionId")
  private String regionId = null;

  @SerializedName("regionName")
  private String regionName = null;

  @SerializedName("alarms")
  private List<RegionAlarmModel> alarms = null;

  public RegionAlarmsHistory regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public RegionAlarmsHistory regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  @Schema(description = "")
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public RegionAlarmsHistory alarms(List<RegionAlarmModel> alarms) {
    this.alarms = alarms;
    return this;
  }

  public RegionAlarmsHistory addAlarmsItem(RegionAlarmModel alarmsItem) {
    if (this.alarms == null) {
      this.alarms = new ArrayList<RegionAlarmModel>();
    }
    this.alarms.add(alarmsItem);
    return this;
  }

   /**
   * Get alarms
   * @return alarms
  **/
  @Schema(description = "")
  public List<RegionAlarmModel> getAlarms() {
    return alarms;
  }

  public void setAlarms(List<RegionAlarmModel> alarms) {
    this.alarms = alarms;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionAlarmsHistory regionAlarmsHistory = (RegionAlarmsHistory) o;
    return Objects.equals(this.regionId, regionAlarmsHistory.regionId) &&
        Objects.equals(this.regionName, regionAlarmsHistory.regionName) &&
        Objects.equals(this.alarms, regionAlarmsHistory.alarms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionId, regionName, alarms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionAlarmsHistory {\n");
    
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    alarms: ").append(toIndentedString(alarms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
