/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.RegionViewModel;
import io.swagger.client.model.V2RegionType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RegionViewModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-15T00:21:04.781159+02:00[Europe/Kiev]")

public class RegionViewModel {
  @SerializedName("regionId")
  private String regionId = null;

  @SerializedName("regionName")
  private String regionName = null;

  @SerializedName("regionType")
  private V2RegionType regionType = null;

  @SerializedName("regionChildIds")
  private List<RegionViewModel> regionChildIds = null;

  public RegionViewModel regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public RegionViewModel regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  @Schema(description = "")
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public RegionViewModel regionType(V2RegionType regionType) {
    this.regionType = regionType;
    return this;
  }

   /**
   * Get regionType
   * @return regionType
  **/
  @Schema(description = "")
  public V2RegionType getRegionType() {
    return regionType;
  }

  public void setRegionType(V2RegionType regionType) {
    this.regionType = regionType;
  }

  public RegionViewModel regionChildIds(List<RegionViewModel> regionChildIds) {
    this.regionChildIds = regionChildIds;
    return this;
  }

  public RegionViewModel addRegionChildIdsItem(RegionViewModel regionChildIdsItem) {
    if (this.regionChildIds == null) {
      this.regionChildIds = new ArrayList<RegionViewModel>();
    }
    this.regionChildIds.add(regionChildIdsItem);
    return this;
  }

   /**
   * Get regionChildIds
   * @return regionChildIds
  **/
  @Schema(description = "")
  public List<RegionViewModel> getRegionChildIds() {
    return regionChildIds;
  }

  public void setRegionChildIds(List<RegionViewModel> regionChildIds) {
    this.regionChildIds = regionChildIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionViewModel regionViewModel = (RegionViewModel) o;
    return Objects.equals(this.regionId, regionViewModel.regionId) &&
        Objects.equals(this.regionName, regionViewModel.regionName) &&
        Objects.equals(this.regionType, regionViewModel.regionType) &&
        Objects.equals(this.regionChildIds, regionViewModel.regionChildIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionId, regionName, regionType, regionChildIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionViewModel {\n");
    
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    regionType: ").append(toIndentedString(regionType)).append("\n");
    sb.append("    regionChildIds: ").append(toIndentedString(regionChildIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
