/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AlertType;
import io.swagger.client.model.TimeSpan;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * RegionAlarmModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-15T00:21:04.781159+02:00[Europe/Kiev]")

public class RegionAlarmModel {
  @SerializedName("regionId")
  private String regionId = null;

  @SerializedName("startDate")
  private OffsetDateTime startDate = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("duration")
  private TimeSpan duration = null;

  @SerializedName("alertType")
  private AlertType alertType = null;

  @SerializedName("regionName")
  private String regionName = null;

  @SerializedName("isContinue")
  private Boolean isContinue = null;

  public RegionAlarmModel regionId(String regionId) {
    this.regionId = regionId;
    return this;
  }

   /**
   * Get regionId
   * @return regionId
  **/
  @Schema(description = "")
  public String getRegionId() {
    return regionId;
  }

  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  public RegionAlarmModel startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @Schema(description = "")
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public RegionAlarmModel endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @Schema(description = "")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public RegionAlarmModel duration(TimeSpan duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public TimeSpan getDuration() {
    return duration;
  }

  public void setDuration(TimeSpan duration) {
    this.duration = duration;
  }

  public RegionAlarmModel alertType(AlertType alertType) {
    this.alertType = alertType;
    return this;
  }

   /**
   * Get alertType
   * @return alertType
  **/
  @Schema(description = "")
  public AlertType getAlertType() {
    return alertType;
  }

  public void setAlertType(AlertType alertType) {
    this.alertType = alertType;
  }

  public RegionAlarmModel regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  @Schema(description = "")
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public RegionAlarmModel isContinue(Boolean isContinue) {
    this.isContinue = isContinue;
    return this;
  }

   /**
   * Get isContinue
   * @return isContinue
  **/
  @Schema(description = "")
  public Boolean isIsContinue() {
    return isContinue;
  }

  public void setIsContinue(Boolean isContinue) {
    this.isContinue = isContinue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionAlarmModel regionAlarmModel = (RegionAlarmModel) o;
    return Objects.equals(this.regionId, regionAlarmModel.regionId) &&
        Objects.equals(this.startDate, regionAlarmModel.startDate) &&
        Objects.equals(this.endDate, regionAlarmModel.endDate) &&
        Objects.equals(this.duration, regionAlarmModel.duration) &&
        Objects.equals(this.alertType, regionAlarmModel.alertType) &&
        Objects.equals(this.regionName, regionAlarmModel.regionName) &&
        Objects.equals(this.isContinue, regionAlarmModel.isContinue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regionId, startDate, endDate, duration, alertType, regionName, isContinue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionAlarmModel {\n");
    
    sb.append("    regionId: ").append(toIndentedString(regionId)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    alertType: ").append(toIndentedString(alertType)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    isContinue: ").append(toIndentedString(isContinue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
