/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets v2RegionType
 */
@JsonAdapter(V2RegionType.Adapter.class)
public enum V2RegionType {
  @SerializedName("State")
  STATE("State"),
  @SerializedName("District")
  DISTRICT("District"),
  @SerializedName("Community")
  COMMUNITY("Community"),
  @SerializedName("Null")
  NULL("Null");

  private String value;

  V2RegionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static V2RegionType fromValue(String input) {
    for (V2RegionType b : V2RegionType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<V2RegionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final V2RegionType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public V2RegionType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return V2RegionType.fromValue((String)(value));
    }
  }
}
