/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AlertModification;
import io.swagger.client.model.AlertRegionModel;
import io.swagger.client.model.RegionAlarmsHistory;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AlertsApi
 */
@Ignore
public class AlertsApiTest {

    private final AlertsApi api = new AlertsApi();

    /**
     * Області, регіони та громади з тривогами
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AlertsGetTest() throws Exception {
        List<AlertRegionModel> response = api.apiV3AlertsGet();

        // TODO: test validations
    }
    /**
     * Отримати останніх 25 тривог регіону
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AlertsRegionHistoryGetTest() throws Exception {
        String regionId = null;
        List<RegionAlarmsHistory> response = api.apiV3AlertsRegionHistoryGet(regionId);

        // TODO: test validations
    }
    /**
     * Статус області/регіону/громади
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AlertsRegionIdGetTest() throws Exception {
        String regionId = null;
        List<AlertRegionModel> response = api.apiV3AlertsRegionIdGet(regionId);

        // TODO: test validations
    }
    /**
     * Перевірка номеру останньої дії. Використовувати для перевірки необхідності оновлювати дані
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3AlertsStatusGetTest() throws Exception {
        AlertModification response = api.apiV3AlertsStatusGet();

        // TODO: test validations
    }
}
