/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.RegionsViewModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RegionsApi
 */
@Ignore
public class RegionsApiTest {

    private final RegionsApi api = new RegionsApi();

    /**
     * Повертає список усіх областей, регіонів та міст
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3RegionsGetTest() throws Exception {
        RegionsViewModel response = api.apiV3RegionsGet();

        // TODO: test validations
    }
}
