/*
 * Ukraine Alert API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * Contact: support@stfalcon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.AlertRegionModel;
import io.swagger.client.model.WebHookModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for WebHookApi
 */
@Ignore
public class WebHookApiTest {

    private final WebHookApi api = new WebHookApi();

    /**
     * Відписка на WebHook про нові сирени та їх відбій
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3WebhookDeleteTest() throws Exception {
        WebHookModel body = null;
        api.apiV3WebhookDelete(body);

        // TODO: test validations
    }
    /**
     * Оновлення WebHook посилання про нові сирени та їх відбій
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3WebhookPatchTest() throws Exception {
        WebHookModel body = null;
        api.apiV3WebhookPatch(body);

        // TODO: test validations
    }
    /**
     * Підписка на WebHook про нові сирени та їх відбій. У вебхукі відпрявляється подія тривоги/відбою (приклад в відповіді \&quot;200\&quot;)
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiV3WebhookPostTest() throws Exception {
        WebHookModel body = null;
        AlertRegionModel response = api.apiV3WebhookPost(body);

        // TODO: test validations
    }
}
